### ISSUE TITLE
NoClassDefFoundError com.microblink.core.MixPanel at Runtime

### ISSUE THREAD

**Issue by dokhanhvu** [BlinkReceipt/blinkreceipt-android#25]
After update to v.1.47 from v1.43, I got error "java.lang.NoClassDefFoundError: com.microblink.core.MixPanel" showed on Toast when I tried to start CameraScanActivity. It did not happen on v1.43 in my current project.
Please Help me out.

Thank you

**Comment by pequots34** [comment]
please make sure you update all sdks ( core, recognizer, camera, etc ). They also require additional work manager and co-routines dependencies.

**Comment by dokhanhvu** [comment]
@pequots34 thank you, I missed work manager and co-routines in my gradle. It work now.

**Comment by pequots34** [comment]
they are in the README files of individual sdks. please be sure to use the versions mentioned there.
