### ISSUE TITLE
Version 1.6.4 datastore-preferences missing library issue

### ISSUE THREAD

**Issue by RamazanM** [BlinkReceipt/blinkreceipt-android#53]
Hi team,
When I upgraded my Blink SDK version to 1.6.4. I got this error while initializing the AccountLinkingClient.
_java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/datastore/preferences/core/PreferencesKeys;_
I solved it by adding _"androidx.datastore:datastore-preferences:1.0.0"_ to my build gradle. But as far as I can see, this is missing on Readme.
Can anyone please add this library to the dependencies list on README.MDs?

**Comment by pequots34** [comment]
Thank you for reporting this. We are working on updating the documentation. Thanks
